### ISSUE TITLE
Non-working "Your Stats" feature

### ISSUE THREAD

**Issue by OleynikAleksandr** [smallcloudai/refact-vscode#230]
When trying to open "Your Stats" from the Refact menu, there is an endless loading — only three moving loading dots are displayed, and the statistics page never appears.

Waiting for a long time does not result in the statistics being shown.

**Environment:**
- Refact extension version: 6.4.4
- Operating system: Windows 11
- Editor: VS Code

How can this issue be resolved? Is there an alternative way to view usage statistics?

## Shell Command Confirmation and Security

**Date:** 2025-05-06  
**Status:** Awaiting response

### Question 4: Unable to disable shell command confirmation

In recent versions of Refact (e.g., 6.4.4), it is impossible to completely disable confirmation for shell commands, even if in the Shell settings and in the `shell.yaml` file:
- The `ask_user` and `deny` fields in the `confirmation` section are empty
- The `allow: ["*"]` section (or similar masks) is added

Nevertheless, when trying to execute any shell command (for example, `mkdir TEMP01`), a confirmation request always appears with the message "Command needs confirmation due to * rule".

Tried:
- Enabling/disabling Shell in the settings
- Restarting the IDE
- Manually editing the `shell.yaml` file (adding the `allow` section with different masks)
- Clearing the cache and restarting the system

Result: confirmation is always required, except for cases where the command is explicitly denied via `deny`.

**Questions:**
- How can I allow shell commands to be executed without confirmation for all or for specific commands?
- Why does the `allow` section in `shell.yaml` not work?
- Is there a way to explicitly allow safe commands (such as `mkdir`, `ls`, `echo`) without confirmation, while keeping confirmation for dangerous ones (`rm`, `del`, `format`, etc.)?
- Is it planned to add such a feature in future versions?

**Environment:**
- Refact version: 6.4.4
- OS: Windows 11
- IDE: VS Code
- shell.yaml:
  ```yaml
  timeout: '30'
  output_filter:
    limit_lines: 400
    limit_chars: 40000
    valuable_top_or_bottom: top
    grep: (?i)error
    grep_context_lines: 5
    remove_from_output: ''
  available:
    on_your_laptop: true
    when_isolated: true
  confirmation:
    ask_user: []
    deny: []
  ```

**Comment:**
The problem is reproducible on different machines and after updating to the latest versions. No similar questions were found in public discussions or GitHub issues.
